export const employees = [
  {
    userId: 'krish',
    jobTitle: 'Developer',
    firstName: 'Krish',
    lastName: 'Lee',
    employeeCode: 'E1',
    region: 'CA',
    phoneNumber: '123456',
    emailAddress: 'krish.lee@learningcontainer.com',
  },
  {
    userId: 'devid',
    jobTitle: 'Developer',
    firstName: 'Devid',
    lastName: 'Rome',
    employeeCode: 'E2',
    region: 'CA',
    phoneNumber: '1111111',
    emailAddress: 'devid.rome@learningcontainer.com',
  },
  {
    userId: 'tin',
    jobTitle: 'Program Directory',
    firstName: 'Tin',
    lastName: 'Jonson',
    employeeCode: 'E3',
    region: 'CA',
    phoneNumber: '2222222',
    emailAddress: 'tin.jonson@learningcontainer.com',
  },
  {
    userId: 'dan',
    jobTitle: 'Developer',
    firstName: 'Daniel',
    lastName: 'Connery',
    employeeCode: 'E4',
    region: 'NA',
    phoneNumber: '9918222',
    emailAddress: 'daniel.connery@learningcontainer.com',
  },
  {
    userId: 'sally',
    jobTitle: 'Thecnical Writter',
    firstName: 'Sally',
    lastName: 'Vega',
    employeeCode: 'E6',
    region: 'NA',
    phoneNumber: '1118277',
    emailAddress: 'sally.vega@learningcontainer.com',
  },
  {
    userId: 'mirian',
    jobTitle: 'Thecnical Writter',
    firstName: 'Mirian',
    lastName: 'Branigan',
    employeeCode: 'E7',
    region: 'OC',
    phoneNumber: '1318077',
    emailAddress: 'mirian.branigan@learningcontainer.com',
  },
  {
    userId: 'marlon',
    jobTitle: 'ITO Director',
    firstName: 'Marlon',
    lastName: 'Wayans',
    employeeCode: 'E8',
    region: 'SA',
    phoneNumber: '8318175',
    emailAddress: 'marlon.wayans@learningcontainer.com',
  },
  {
    userId: 'kevin',
    jobTitle: 'Devops',
    firstName: 'Kevin',
    lastName: 'Arnold',
    employeeCode: 'E9',
    region: 'CA',
    phoneNumber: '2312175',
    emailAddress: 'kevin.arnold@learningcontainer.com',
  },
  {
    userId: 'jim',
    jobTitle: 'Recruiter',
    firstName: 'Jim',
    lastName: 'Carrey',
    employeeCode: 'E5',
    region: 'CA',
    phoneNumber: '2352171',
    emailAddress: 'jim.carrey@learningcontainer.com',
  },
  {
    userId: 'carly',
    jobTitle: 'Developer',
    firstName: 'Carly',
    lastName: 'Smith',
    employeeCode: 'E10',
    region: 'NA',
    phoneNumber: '7752171',
    emailAddress: 'carly.smith@learningcontainer.com',
  },
  {
    userId: 'brandom',
    jobTitle: 'Automation',
    firstName: 'Brandom',
    lastName: 'Boyd',
    employeeCode: 'E11',
    region: 'NA',
    phoneNumber: '7756173',
    emailAddress: 'brandom.boyd@learningcontainer.com',
  },
  {
    userId: 'john',
    jobTitle: 'Requeriments Engineer',
    firstName: 'John',
    lastName: 'Frusciante',
    employeeCode: 'E12',
    region: 'NA',
    phoneNumber: '3756173',
    emailAddress: 'john.frusciante@learningcontainer.com',
  },
];
