export const PRODUCTS = [
  {
    category: 'Sporting Goods',
    price: '$49.99',
    stocked: true,
    name: 'Football',
  },
  {
    category: 'Sporting Goods',
    price: '$9.99',
    stocked: true,
    name: 'Baseball',
  },
  {
    category: 'Sporting Goods',
    price: '$29.99',
    stocked: false,
    name: 'Basketball',
  },
  {
    category: 'Electronics',
    price: '$99.99',
    stocked: true,
    name: 'iPod Touch',
  },
  {
    category: 'Electronics',
    price: '$399.99',
    stocked: false,
    name: 'iPhone 5',
  },
  {
    category: 'Electronics',
    price: '$199.99',
    stocked: true,
    name: 'Nexus 7',
  },
  {
    category: 'Music',
    price: '$19.19',
    stocked: true,
    name: 'Californication',
  },
  {
    category: 'Music',
    price: '$17.11',
    stocked: false,
    name: 'Make Yourself',
  },
  {
    category: 'Music',
    price: '$21.56',
    stocked: false,
    name: 'Science',
  },
  {
    category: 'Music',
    price: '$11.25',
    stocked: true,
    name: 'Camino Palmero',
  },
  {
    category: 'Music',
    price: '$16.39',
    stocked: true,
    name: 'Fungus Amongus',
  },
  {
    category: 'Movies',
    price: '$9.54',
    stocked: false,
    name: 'Avengers - Endgame',
  },
  {
    category: 'Movies',
    price: '$19.19',
    stocked: true,
    name: 'Star Wars',
  },
  {
    category: 'Movies',
    price: '$26.15',
    stocked: true,
    name: 'Lord of the Rings',
  },
  {
    category: 'Movies',
    price: '$13.18',
    stocked: true,
    name: 'Sherlock Holmes',
  },
];
